In [4]:
# ELECTRICAL GRID STABILITY CLASSIFICATION PROBLEM

# STEP 1: Import libraries

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    roc_auc_score,
    precision_score,
    recall_score,
    f1_score,
    matthews_corrcoef,
    confusion_matrix,
    classification_report
)

print("Libraries imported successfully!")

# LOAD THE ORIGINAL DATASET

data = pd.read_csv("Grid stability test dataset.csv")

print("\nOriginal Dataset")
print("----------------")
print("Number of rows    :", data.shape[0])
print("Number of columns :", data.shape[1])

print("\nFirst 5 rows:")
display(data.head())

# CHECK THE DATASET

print("\nColumn names:")
print(data.columns.tolist())

print("\nMissing values:")
print(data.isnull().sum())

print("\nTarget distribution:")
print(data["stabf"].value_counts())

# CREATE TRAINING AND TEST DATA

# 80% Training data
# 20% Test data

train_data, test_data = train_test_split(
    data,
    test_size=0.20,
    random_state=42,
    stratify=data["stabf"]
)

print("\nTraining data size:", train_data.shape)
print("Test data size    :", test_data.shape)

print("TRAINING DATASET - First 10 Rows")
display(train_data.head(10))

print("TEST DATASET - First 10 Rows")
display(test_data.head(10))

# Save the two datasets

train_data.to_csv(
    "Grid_Stability_Training.csv",
    index=False
)

test_data.to_csv(
    "Grid_Stability_Test.csv",
    index=False
)

print("\nTraining and Test files saved successfully!")

# SELECT THE 12 INPUT FEATURES

features = [
    "tau1",
    "tau2",
    "tau3",
    "tau4",
    "p1",
    "p2",
    "p3",
    "p4",
    "g1",
    "g2",
    "g3",
    "g4"
]
# Training input
X_train = train_data[features]

# Training target
y_train = train_data["stabf"]

# Test input
X_test = test_data[features]

# Test target
y_test = test_data["stabf"]

print("\nNumber of input features:", len(features))
print("Training samples:", len(X_train))
print("Test samples:", len(X_test))

# ENCODE STABLE / UNSTABLE

encoder = LabelEncoder()

# Fit using training target
y_train = encoder.fit_transform(y_train)

# Use the same encoder for test target
y_test = encoder.transform(y_test)

print("\nTarget classes:")
print(encoder.classes_)

print("0 =", encoder.classes_[0])
print("1 =", encoder.classes_[1])

# STANDARDIZE THE DATA

# Scaling is required mainly for Logistic Regression and KNN.

scaler = StandardScaler()

# Fit scaler only using training data
X_train_scaled = scaler.fit_transform(X_train)

# Apply the same scaler to test data
X_test_scaled = scaler.transform(X_test)

print("\nFeature scaling completed!")

# LOGISTIC REGRESSION

logistic_model = LogisticRegression(
    max_iter=1000
)

logistic_model.fit(
    X_train_scaled,
    y_train
)

logistic_prediction = logistic_model.predict(
    X_test_scaled
)

logistic_probability = logistic_model.predict_proba(
    X_test_scaled
)[:, 1]

print("\nLogistic Regression completed!")


# DECISION TREE

decision_tree = DecisionTreeClassifier(
    random_state=42
)

decision_tree.fit(
    X_train,
    y_train
)

tree_prediction = decision_tree.predict(
    X_test
)

tree_probability = decision_tree.predict_proba(
    X_test
)[:, 1]

print("Decision Tree completed!")


# K-NEAREST NEIGHBOUR

knn_model = KNeighborsClassifier(
    n_neighbors=5
)

knn_model.fit(
    X_train_scaled,
    y_train
)

knn_prediction = knn_model.predict(
    X_test_scaled
)

knn_probability = knn_model.predict_proba(
    X_test_scaled
)[:, 1]

print("KNN completed!")

# GAUSSIAN NAIVE BAYES

naive_bayes = GaussianNB()

naive_bayes.fit(
    X_train,
    y_train
)

nb_prediction = naive_bayes.predict(
    X_test
)

nb_probability = naive_bayes.predict_proba(
    X_test
)[:, 1]

print("Gaussian Naive Bayes completed!")


# RANDOM FOREST

random_forest = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

random_forest.fit(
    X_train,
    y_train
)

rf_prediction = random_forest.predict(
    X_test
)

rf_probability = random_forest.predict_proba(
    X_test
)[:, 1]

print("Random Forest completed!")

# CALCULATE RESULTS FOR ALL FIVE MODELS

# Logistic Regression

logistic_accuracy = accuracy_score(
    y_test,
    logistic_prediction
)

logistic_auc = roc_auc_score(
    y_test,
    logistic_probability
)

logistic_precision = precision_score(
    y_test,
    logistic_prediction,
    zero_division=0
)

logistic_recall = recall_score(
    y_test,
    logistic_prediction,
    zero_division=0
)

logistic_f1 = f1_score(
    y_test,
    logistic_prediction,
    zero_division=0
)

logistic_mcc = matthews_corrcoef(
    y_test,
    logistic_prediction
)


# Decision Tree

tree_accuracy = accuracy_score(
    y_test,
    tree_prediction
)

tree_auc = roc_auc_score(
    y_test,
    tree_probability
)

tree_precision = precision_score(
    y_test,
    tree_prediction,
    zero_division=0
)

tree_recall = recall_score(
    y_test,
    tree_prediction,
    zero_division=0
)

tree_f1 = f1_score(
    y_test,
    tree_prediction,
    zero_division=0
)

tree_mcc = matthews_corrcoef(
    y_test,
    tree_prediction
)


# KNN

knn_accuracy = accuracy_score(
    y_test,
    knn_prediction
)

knn_auc = roc_auc_score(
    y_test,
    knn_probability
)

knn_precision = precision_score(
    y_test,
    knn_prediction,
    zero_division=0
)

knn_recall = recall_score(
    y_test,
    knn_prediction,
    zero_division=0
)

knn_f1 = f1_score(
    y_test,
    knn_prediction,
    zero_division=0
)

knn_mcc = matthews_corrcoef(
    y_test,
    knn_prediction
)


# Gaussian Naive Bayes

nb_accuracy = accuracy_score(
    y_test,
    nb_prediction
)

nb_auc = roc_auc_score(
    y_test,
    nb_probability
)

nb_precision = precision_score(
    y_test,
    nb_prediction,
    zero_division=0
)

nb_recall = recall_score(
    y_test,
    nb_prediction,
    zero_division=0
)

nb_f1 = f1_score(
    y_test,
    nb_prediction,
    zero_division=0
)

nb_mcc = matthews_corrcoef(
    y_test,
    nb_prediction
)


# Random Forest

rf_accuracy = accuracy_score(
    y_test,
    rf_prediction
)

rf_auc = roc_auc_score(
    y_test,
    rf_probability
)

rf_precision = precision_score(
    y_test,
    rf_prediction,
    zero_division=0
)

rf_recall = recall_score(
    y_test,
    rf_prediction,
    zero_division=0
)

rf_f1 = f1_score(
    y_test,
    rf_prediction,
    zero_division=0
)

rf_mcc = matthews_corrcoef(
    y_test,
    rf_prediction
)

# CREATE FINAL COMPARISON TABLE

results = pd.DataFrame({

    "Model": [
        "Logistic Regression",
        "Decision Tree",
        "K-Nearest Neighbour",
        "Gaussian Naive Bayes",
        "Random Forest"
    ],

    "Accuracy": [
        logistic_accuracy,
        tree_accuracy,
        knn_accuracy,
        nb_accuracy,
        rf_accuracy
    ],

    "AUC Score": [
        logistic_auc,
        tree_auc,
        knn_auc,
        nb_auc,
        rf_auc
    ],

    "Precision": [
        logistic_precision,
        tree_precision,
        knn_precision,
        nb_precision,
        rf_precision
    ],

    "Recall": [
        logistic_recall,
        tree_recall,
        knn_recall,
        nb_recall,
        rf_recall
    ],

    "F1 Score": [
        logistic_f1,
        tree_f1,
        knn_f1,
        nb_f1,
        rf_f1
    ],

    "MCC Score": [
        logistic_mcc,
        tree_mcc,
        knn_mcc,
        nb_mcc,
        rf_mcc
    ]
})

# Round values to four decimal places

results = results.round(4)

#  DISPLAY FINAL COMPARISON

print("\n")
print("=" * 90)
print("FINAL COMPARISON OF FIVE MACHINE LEARNING MODELS")
print("=" * 90)

display(results)



# FIND THE BEST MODEL

# F1 Score is used to identify the best overall model.

best_index = results["F1 Score"].idxmax()

best_model = results.loc[
    best_index,
    "Model"
]


# HIGHLIGHT THE BEST MODEL

def highlight_best(row):

    if row.name == best_index:
        return ["background-color: lightgreen"] * len(row)

    return [""] * len(row)


print("\nBest model is highlighted in green:")

display(
    results.style.apply(
        highlight_best,
        axis=1
    )
)


# DISPLAY BEST MODEL DETAILS
print("\n")
print("=" * 50)
print("BEST PERFORMING MODEL")
print("=" * 50)

print("Best Model :", best_model)
print("Accuracy   :", results.loc[best_index, "Accuracy"])
print("AUC Score  :", results.loc[best_index, "AUC Score"])
print("Precision  :", results.loc[best_index, "Precision"])
print("Recall     :", results.loc[best_index, "Recall"])
print("F1 Score   :", results.loc[best_index, "F1 Score"])
print("MCC Score  :", results.loc[best_index, "MCC Score"])


# SAVE FINAL RESULTS

results.to_csv(
    "Grid_Stability_ML_Results.csv",
    index=False
)

print("\nFinal results saved as:")
print("Grid_Stability_ML_Results.csv")


# TEST ONE NEW GRID SAMPLE

# Enter one new sample containing the 12 input features.

new_sample = pd.DataFrame([{

    "tau1": 2.0,
    "tau2": 1.0,
    "tau3": 0.0,
    "tau4": 0.5,

    "p1": 3.0,
    "p2": -1.0,
    "p3": -1.2,
    "p4": -0.8,

    "g1": 0.6,
    "g2": 0.7,
    "g3": 0.8,
    "g4": 0.9
}])


# Scale the sample for Logistic Regression and KNN

new_sample_scaled = scaler.transform(
    new_sample[features]
)


# Make predictions

new_predictions = {

    "Logistic Regression":
        logistic_model.predict(new_sample_scaled)[0],

    "Decision Tree":
        decision_tree.predict(new_sample[features])[0],

    "K-Nearest Neighbour":
        knn_model.predict(new_sample_scaled)[0],

    "Gaussian Naive Bayes":
        naive_bayes.predict(new_sample[features])[0],

    "Random Forest":
        random_forest.predict(new_sample[features])[0]
}

# Display predictions

print("\n")
print("=" * 50)
print("PREDICTION FOR ONE NEW GRID SAMPLE")
print("=" * 50)

for model_name, prediction in new_predictions.items():

    result = encoder.inverse_transform([prediction])[0]

    print(
        model_name,
        ":",
        result
    )

Libraries imported successfully!

Original Dataset
----------------
Number of rows    : 10000
Number of columns : 14

First 5 rows:

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stab,stabf
0,2.959060,3.079885,8.381025,9.780754,3.763085,-0.782604,-1.257395,-1.723086,0.650456,0.859578,0.887445,0.958034,0.055347,unstable
1,9.304097,4.902524,3.047541,1.369357,5.067812,-1.940058,-1.872742,-1.255012,0.413441,0.862414,0.562139,0.781760,-0.005957,stable
2,8.971707,8.848428,3.046479,1.214518,3.405158,-1.207456,-1.277210,-0.920492,0.163041,0.766689,0.839444,0.109853,0.003471,unstable
3,0.716415,7.669600,4.486641,2.340563,3.963791,-1.027473,-1.938944,-0.997374,0.446209,0.976744,0.929381,0.362718,0.028871,unstable
4,3.134112,7.608772,4.943759,9.857573,3.525811,-1.125531,-1.845975,-0.554305,0.797110,0.455450,0.656947,0.820923,0.049860,unstable

Column names:
['tau1', 'tau2', 'tau3', 'tau4', 'p1', 'p2', 'p3', 'p4', 'g1', 'g2', 'g3', 'g4', 'stab', 'stabf']

Missing values:
tau1     0
tau2     0
tau3     0
tau4     0
p1       0
p2       0
p3       0
p4       0
g1       0
g2       0
g3       0
g4       0
stab     0
stabf    0
dtype: int64

Target distribution:
stabf
unstable    6380
stable      3620
Name: count, dtype: int64

Training data size: (8000, 14)
Test data size    : (2000, 14)
TRAINING DATASET - First 10 Rows

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stab,stabf
5244,4.966299,4.536913,4.329575,5.996910,4.873277,-1.859493,-1.969932,-1.043852,0.806279,0.328946,0.224657,0.905824,0.063384,unstable
9265,5.874752,6.636065,9.542791,4.029977,3.233809,-0.633601,-1.583444,-1.016763,0.458043,0.597933,0.127654,0.464095,0.023861,unstable
6156,9.718050,1.568638,9.928525,3.477468,3.697184,-1.360641,-1.415556,-0.920987,0.857598,0.746406,0.360908,0.612772,0.006505,unstable
2357,9.081008,9.861482,8.578244,3.006405,3.758945,-1.752541,-1.282223,-0.724180,0.886878,0.630460,0.348931,0.329132,0.054079,unstable
8051,2.684229,6.891085,1.730129,4.432898,4.389082,-1.308068,-1.554610,-1.526403,0.881586,0.128302,0.431798,0.628442,-0.005773,stable
6208,6.614117,9.100041,5.344674,0.706861,4.576136,-1.931064,-0.779733,-1.865338,0.082063,0.179090,0.353525,0.604223,-0.049457,stable
2244,1.376453,7.160785,9.638368,6.298357,5.378774,-1.883743,-1.705492,-1.789539,0.354360,0.730219,0.317424,0.346801,0.015863,unstable
2754,4.292177,2.903450,7.558527,6.519874,4.650997,-1.105046,-1.759771,-1.786180,0.595198,0.723041,0.208128,0.188746,-0.002880,stable
2925,8.653505,5.736916,6.660231,9.087241,3.077114,-0.951742,-1.417577,-0.707795,0.072072,0.295937,0.131195,0.780050,0.017346,unstable
5769,1.933401,6.665227,0.683171,2.954398,4.136292,-1.299329,-1.652878,-1.184085,0.619160,0.327869,0.121567,0.972416,-0.035632,stable

TEST DATASET - First 10 Rows

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stab,stabf
6073,3.390366,0.825087,8.844493,9.202492,2.925125,-1.332589,-0.720396,-0.872140,0.449769,0.195689,0.785641,0.964839,0.045997,unstable
4507,4.994762,2.821639,0.760455,9.206182,3.888964,-0.880448,-1.355102,-1.653415,0.728578,0.275257,0.254377,0.264639,-0.031474,stable
5739,7.207571,5.806705,2.041467,3.652464,4.217611,-0.998719,-1.329074,-1.889817,0.270999,0.578486,0.396148,0.445916,-0.001653,stable
2894,2.773448,0.622441,4.561937,0.700199,4.811384,-1.353995,-1.935951,-1.521438,0.209793,0.473838,0.141949,0.812419,-0.042292,stable
7817,7.982703,3.582483,3.686522,3.414636,2.940471,-0.546441,-1.053662,-1.340369,0.892353,0.088834,0.163716,0.345950,0.006877,unstable
2386,1.504612,3.192776,8.470990,2.720803,3.871381,-1.664839,-0.774288,-1.432254,0.426831,0.726228,0.472619,0.054853,-0.045002,stable
4131,7.291729,1.153307,1.305038,6.479709,4.063145,-1.900303,-0.564353,-1.598489,0.745317,0.082858,0.305596,0.081728,-0.029861,stable
5094,7.826265,0.808521,7.278371,4.701954,2.204264,-0.684501,-0.523832,-0.995931,0.334086,0.199443,0.728861,0.466593,0.019545,unstable
7863,6.227423,1.994046,3.520582,1.383831,4.261405,-1.473036,-1.378019,-1.410350,0.299488,0.561065,0.066424,0.722682,-0.039928,stable
5315,7.678862,4.725106,2.981270,3.082085,3.528499,-1.803046,-1.198316,-0.527137,0.172663,0.715077,0.269251,0.620836,0.002937,unstable

Training and Test files saved successfully!

Number of input features: 12
Training samples: 8000
Test samples: 2000

Target classes:
['stable' 'unstable']
0 = stable
1 = unstable

Feature scaling completed!

Logistic Regression completed!
Decision Tree completed!
KNN completed!
Gaussian Naive Bayes completed!
Random Forest completed!


==========================================================================================
FINAL COMPARISON OF FIVE MACHINE LEARNING MODELS
==========================================================================================

,Model,Accuracy,AUC Score,Precision,Recall,F1 Score,MCC Score
0,Logistic Regression,0.8200,0.8920,0.8408,0.8856,0.8626,0.6039
1,Decision Tree,0.8495,0.8369,0.8818,0.8824,0.8821,0.6741
2,K-Nearest Neighbour,0.8625,0.9290,0.8547,0.9451,0.8977,0.6980
3,Gaussian Naive Bayes,0.8445,0.9210,0.8395,0.9350,0.8847,0.6570
4,Random Forest,0.9240,0.9806,0.9226,0.9616,0.9417,0.8342

Best model is highlighted in green:

==================================================
BEST PERFORMING MODEL
==================================================
Best Model : Random Forest
Accuracy   : 0.924
AUC Score  : 0.9806
Precision  : 0.9226
Recall     : 0.9616
F1 Score   : 0.9417
MCC Score  : 0.8342

Final results saved as:
Grid_Stability_ML_Results.csv


==================================================
PREDICTION FOR ONE NEW GRID SAMPLE
==================================================
Logistic Regression : stable
Decision Tree : stable
K-Nearest Neighbour : stable
Gaussian Naive Bayes : stable
Random Forest : stable